const { validationResult } = require('express-validator');
const { callGemini } = require('../services/geminiService');
const Blog = require('../models/Blog');

const cleanGeneratedText = (text) => {
  if (!text) return '';

  return text
    .replace(/^\s*#{1,6}\s*/gm, '')
    .replace(/^\s*[\*\-\+]\s*/gm, '')
    .replace(/\*{1,3}(.+?)\*{1,3}/g, '$1')
    .replace(/_{2,}/g, '')
    .replace(/\r\n|\r/g, '\n')
    .replace(/\n{3,}/g, '\n\n')
    .trim();
};

const inferCategory = (topic) => {
  const normalized = topic.toLowerCase();

  const mapping = [
    { keywords: ['ai', 'technology', 'software', 'programming', 'cloud', 'computer'], category: 'Technology' },
    { keywords: ['learning', 'school', 'education', 'teaching', 'study'], category: 'Education' },
    { keywords: ['health', 'fitness', 'medicine', 'wellness', 'mental'], category: 'Health' },
    { keywords: ['sports', 'football', 'basketball', 'soccer', 'athlete'], category: 'Sports' },
    { keywords: ['fashion', 'lifestyle', 'home', 'beauty'], category: 'Lifestyle' },
    { keywords: ['business', 'startup', 'marketing', 'entrepreneur'], category: 'Business' },
    { keywords: ['travel', 'tourism', 'destination', 'adventure', 'holiday'], category: 'Travel' },
    { keywords: ['money', 'investment', 'stocks', 'banking', 'crypto', 'finance'], category: 'Finance' },
    { keywords: ['entertainment', 'movies', 'music', 'celebrity', 'gaming'], category: 'Entertainment' },
  ];

  const match = mapping.find((item) =>
    item.keywords.some((keyword) => normalized.includes(keyword))
  );

  return match ? match.category : 'General';
};

const checkValidation = (req, res) => {
  const errors = validationResult(req);

  if (!errors.isEmpty()) {
    res.status(422).json({
      success: false,
      errors: errors.array(),
    });
    return false;
  }

  return true;
};

const generateBlog = async (req, res, next) => {
  if (!checkValidation(req, res)) return;

  try {
    const { topic, category } = req.body;

    const prompt = `
Create an original blog post about: ${topic}

Requirements:
- 500 to 700 words.
- Start with an engaging introduction.
- Use clear paragraphs and useful subtopics.
- End with a practical conclusion.
- Do not use markdown symbols such as #, *, or bullet characters.
- Do not mention that the content was generated by AI.
- Return only the blog content.
`;

    const result = cleanGeneratedText(await callGemini(prompt));

    if (!result) {
      return res.status(502).json({
        success: false,
        message: 'AI returned empty content',
      });
    }

    const blog = await Blog.create({
      title: `Guide to ${topic.trim()}`,
      content: result,
      category: category?.trim() || inferCategory(topic),
      author: req.user._id,
      authorName: req.user.name,
    });

    const populated = await blog.populate('author', 'name email');

    res.status(201).json({
      success: true,
      message: 'AI blog generated successfully',
      blog: populated,
    });
  } catch (error) {
    next(error);
  }
};

const summarizeBlog = async (req, res, next) => {
  if (!checkValidation(req, res)) return;

  try {
    const { content } = req.body;

    const prompt = `
Summarize the following blog content in 80 to 120 words.
Use simple, natural language.
Return only the summary.

BLOG:
${content}
`;

    const summary = cleanGeneratedText(await callGemini(prompt));

    res.json({
      success: true,
      summary,
    });
  } catch (error) {
    next(error);
  }
};

module.exports = {
  generateBlog,
  summarizeBlog,
};
